import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Card from '../components/Card';


export default function Home() {
  return (
    <div>
      <Head>
        <title>ANTHONY SIM | LIFE & CODE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Card />
    </div>
  )
}
